-- Fazendo update na tabela sobremesa.
UPDATE sobremesa SET calorias = 500 WHERE id = 1;
UPDATE sobremesa SET calorias = 450 WHERE origem = 'Brasil';
UPDATE sobremesa SET calorias = 350 WHERE origem = 'EUA';
UPDATE sobremesa SET calorias = 250 WHERE origem = 'Italia';
UPDATE sobremesa SET calorias = 300 WHERE id = 4;
UPDATE sobremesa SET calorias = 350 WHERE anoCriacao = 1500;
UPDATE sobremesa SET calorias = 450 WHERE nome = 'cocada';
UPDATE sobremesa SET calorias = 150 WHERE nome = 'sonho';
UPDATE sobremesa SET calorias = 400 WHERE id = 9;
UPDATE sobremesa SET calorias = 300 WHERE origem = 'Japao';
UPDATE sobremesa SET calorias = 400 WHERE nome = 'Chocotorta';
UPDATE sobremesa SET calorias = 200 WHERE nome = 'kulfi';
UPDATE sobremesa SET calorias = 350 WHERE id = 13;
UPDATE sobremesa SET calorias = 250 WHERE nome = 'Laddu';
UPDATE sobremesa SET calorias = 400 WHERE nome = 'Sandesh';
UPDATE sobremesa SET calorias = 300 WHERE id = 16;
UPDATE sobremesa SET calorias = 350 WHERE nome = 'Modak';
UPDATE sobremesa SET calorias = 250 WHERE nome = 'Rabri';
UPDATE sobremesa SET calorias = 400 WHERE id = 18;
UPDATE sobremesa SET calorias = 300 WHERE origem = 'India';
UPDATE sobremesa SET anoCriacao = 1900 WHERE id = 7;
UPDATE sobremesa SET calorias = 700 WHERE origem = "Brasil";
UPDATE sobremesa SET nome = "Brigadeiro" WHERE calorias = 150;
UPDATE sobremesa SET origem = "Brasil" WHERE id = 8;
UPDATE sobremesa SET anoCriacao = 2017 WHERE id = 9;
UPDATE sobremesa SET calorias = 700 WHERE origem = "Brasil";
UPDATE sobremesa SET nome = "Sorvete" WHERE anoCriacao = 1000;
UPDATE sobremesa SET origem = "Portugal" WHERE nome = "Pavê";   
UPDATE sobremesa SET anoCriacao = 1987 WHERE id = 11;
UPDATE sobremesa SET calorias = 700 WHERE origem = "México";
UPDATE sobremesa SET nome = "Pudim" WHERE calorias = > 400;
UPDATE sobremesa SET origem = "Brasil" WHERE id = 12;
UPDATE sobremesa SET calorias = 100 WHERE anoCriacao < 1999;   
UPDATE sobremesa SET nome = "Cocada" WHERE origem = "Argentina";
UPDATE sobremesa SET origem = "França" WHERE id = 50;
UPDATE sobremesa SET anoCriacao = 2007 WHERE calorias = < 200;
UPDATE sobremesa SET nome = "Merengue" WHERE id = 89;
UPDATE sobremesa SET origem = "México" WHERE anoCriacao = 1800;
UPDATE sobremesa SET calorias = 300 WHERE origem = "Grécia";
UPDATE sobremesa SET nome = "Barfi" WHERE id = 97;
UPDATE sobremesa SET anoCriacao = 2000 WHERE calorias = 200;
UPDATE sobremesa SET nome = 'Mousse de Chocolate' WHERE nome = 'Mousse de Maracuja';
UPDATE sobremesa SET anoCriacao = 1930 WHERE id = 2;
UPDATE sobremesa SET anoCriacao = 1500 WHERE calorias = 350;
UPDATE sobremesa SET origem = 'Austrália' WHERE anoCriacao = 1900;
UPDATE sobremesa SET origem = 'França' WHERE id = 3;
UPDATE sobremesa SET nome = 'Gelato' WHERE id = 4;
UPDATE sobremesa SET calorias = 500 WHERE nome = 'Tiramisu';
UPDATE sobremesa SET nome = 'Pastelzinho Doce' WHERE anoCriacao = 1837;
UPDATE sobremesa SET calorias = 450 WHERE origem = 'Brasil';
UPDATE sobremesa SET origem = 'Japão' WHERE nome = 'Mochi';
UPDATE sobremesa SET anoCriacao = 2000 WHERE nome = 'Cheesecake';
UPDATE sobremesa SET nome = 'Biscoito de Amêndoas' WHERE origem = 'França';
UPDATE sobremesa SET anoCriacao = 1985 WHERE origem = 'EUA';
UPDATE sobremesa SET calorias = 380 WHERE anoCriacao = 1500;
UPDATE sobremesa SET calorias = 300 WHERE origem = 'Turquia';
UPDATE sobremesa SET calorias = 250 WHERE anoCriacao = 1980;
UPDATE sobremesa SET nome = 'Pudim de Doce de Leite' WHERE calorias = 300;
UPDATE sobremesa SET origem = 'Egito' WHERE calorias = 400;
UPDATE sobremesa SET calorias = 420 WHERE id = 1;
UPDATE sobremesa SET calorias = 500 WHERE nome = 'Tiramisu';
UPDATE sobremesa SET anoCriacao = 1930 WHERE nome = 'Cheesecake';
UPDATE sobremesa SET origem = 'França' WHERE nome = 'Creme Brulee';
UPDATE sobremesa SET calorias = 380 WHERE nome = 'Brownie';
UPDATE sobremesa SET nome = 'Brigadeiro Gourmet', calorias = 250 WHERE origem = 'Brasil';
UPDATE sobremesa SET calorias = 450 WHERE nome = 'Pavlova';
UPDATE sobremesa SET nome = 'Mochi Tradicional', origem = 'Japão' WHERE anoCriacao = 794;
UPDATE sobremesa SET anoCriacao = 1500 WHERE nome = 'Rabanada';
UPDATE sobremesa SET calorias = 400, origem = 'Grécia' WHERE origem = 'Baklava';
UPDATE sobremesa SET calorias = 370 WHERE nome = 'Churros';
UPDATE sobremesa SET calorias = 320 WHERE nome = 'Pudim';
UPDATE sobremesa SET anoCriacao = 1900 WHERE nome = 'Sorvete';
UPDATE sobremesa SET origem = 'Itália' WHERE nome = 'Panna Cotta';
UPDATE sobremesa SET nome = 'Mousse de Maracujá com Chantilly', calorias = 450 WHERE nome = 'Mousse de Maracuja';
UPDATE sobremesa SET origem = 'França' WHERE nome = 'Macaron';
UPDATE sobremesa SET calorias = 420 WHERE nome = 'Quindim';
UPDATE sobremesa SET anoCriacao = 1750 WHERE origem = 'Portugal';
UPDATE sobremesa SET calorias = 380 WHERE nome = 'Banoffee Pie';
UPDATE sobremesa SET calorias = 250, origem = 'Brasil' WHERE nome = 'Beijinho';
UPDATE sobremesa SET anoCriacao = 1950, calorias = 400 WHERE nome = 'Cocada';
UPDATE sobremesa SET nome = 'Pastel de Nata', calorias = 300 WHERE nome = 'Pastel de Nata'; 
UPDATE sobremesa SET origem = 'Inglaterra' WHERE nome = 'Banoffee Pie';
UPDATE sobremesa SET calorias = 350 WHERE nome = 'Manjar Branco';
UPDATE sobremesa SET nome = 'Baba de Moça', calorias = 250 WHERE nome = 'Baba de Moça';
UPDATE sobremesa SET origem = 'Brasil' WHERE nome = 'Pe de Moleque';
UPDATE sobremesa SET calorias = 400 WHERE nome = 'Beijinho';
UPDATE sobremesa SET nome = 'Cajuzinho', calorias = 200 WHERE nome = 'Cajuzinho';
UPDATE sobremesa SET origem = 'Brasil' WHERE nome = 'Canjica';
UPDATE sobremesa SET calorias = 250 WHERE nome = 'Curau';
UPDATE sobremesa SET nome = 'Arroz Doce', calorias = 200 WHERE nome = 'Arroz Doce';
UPDATE sobremesa SET origem = 'Portugal' WHERE nome = 'Rabanada';
UPDATE sobremesa SET calorias = 350 WHERE nome = 'Sonho';
UPDATE sobremesa SET nome = 'Pudim de Leite', calorias = 300 WHERE nome = 'Pudim de Leite';
UPDATE sobremesa SET origem = 'Brasil' WHERE nome = 'Manjar de Coco';
UPDATE sobremesa SET calorias = 250 WHERE nome = 'Baba de Camelo';
UPDATE sobremesa SET nome = 'Pe de Moleque de Chocolate', calorias = 350 WHERE nome = 'Pe de Moleque de Chocolate';
UPDATE sobremesa SET origem = 'Brasil' WHERE nome = 'Beijinho de Coco';
UPDATE sobremesa SET calorias = 200 WHERE nome = 'Cajuzinho de Amendoim';
UPDATE sobremesa SET nome = 'Canjica com Coco', calorias = 250 WHERE nome = 'Canjica com Coco';
UPDATE sobremesa SET origem = 'Brasil' WHERE nome = 'Curau de Milho';