--Deletar dados da tabela sobremesa.
DELETE FROM sobremesa WHERE origem = 'Italia';
DELETE FROM sobremesa WHERE anoCriacao < 1900;
DELETE FROM sobremesa WHERE calorias > 300;
DELETE FROM sobremesa WHERE origem = 'EUA';
DELETE FROM sobremesa WHERE nome = 'Pudim' AND calorias < 400;
DELETE FROM sobremesa WHERE anoCriacao = 1980;
DELETE FROM sobremesa WHERE origem = 'Brasil' AND calorias > 250;
DELETE FROM sobremesa WHERE nome = 'Sorvete' AND origem = 'China';
DELETE FROM sobremesa WHERE calorias BETWEEN 200 AND 300;
DELETE FROM sobremesa WHERE origem = 'França' AND anoCriacao > 1500;
DELETE FROM sobremesa WHERE nome LIKE '%de Leite%';
DELETE FROM sobremesa WHERE calorias = 150;
DELETE FROM sobremesa WHERE nome = 'Churros' AND origem = 'Espanha';
DELETE FROM sobremesa WHERE anoCriacao < 1700;
DELETE FROM sobremesa WHERE origem = 'Portugal' AND calorias <= 300;
DELETE FROM sobremesa WHERE nome = 'Mousse de Maracuja';
DELETE FROM sobremesa WHERE origem = 'Nova Zelândia' AND anoCriacao < 1950;
DELETE FROM sobremesa WHERE calorias > 400;
DELETE FROM sobremesa WHERE nome = 'Brownie' AND origem = 'EUA';
DELETE FROM sobremesa WHERE nome = 'Macaron' AND anoCriacao < 1600;
DELETE FROM sobremesa WHERE origem = 'Espanha' AND calorias < 300;
DELETE FROM sobremesa WHERE nome = 'Panna Cotta' AND calorias <= 250;
DELETE FROM sobremesa WHERE origem = 'Japao' AND anoCriacao > 1900;
DELETE FROM sobremesa WHERE nome = 'Beijinho' AND calorias < 250;
DELETE FROM sobremesa WHERE origem = 'Brasil' AND anoCriacao = 1940;
DELETE FROM sobremesa WHERE nome = 'Quindim' AND calorias = 300;
DELETE FROM sobremesa WHERE origem = 'Argentina' AND anoCriacao < 1900;
DELETE FROM sobremesa WHERE calorias > 350;
DELETE FROM sobremesa WHERE nome = 'Banoffee Pie' AND origem = 'Inglaterra';
DELETE FROM sobremesa WHERE nome = 'Gelatina' AND anoCriacao < 1900;
DELETE FROM sobremesa WHERE origem = 'Filipinas' AND calorias < 300;
DELETE FROM sobremesa WHERE nome = 'Malva Pudding' AND origem = 'Africa do Sul';
DELETE FROM sobremesa WHERE nome = 'Tiramisu' AND anoCriacao > 1950;
DELETE FROM sobremesa WHERE origem = 'India' AND calorias > 300;
DELETE FROM sobremesa WHERE nome LIKE 'Cajuzinho%';
DELETE FROM sobremesa WHERE origem = 'Grecia' AND anoCriacao < 1800;
DELETE FROM sobremesa WHERE calorias = 250;
DELETE FROM sobremesa WHERE nome = 'Capirotada' AND origem = 'Mexico';
DELETE FROM sobremesa WHERE origem = 'Turquia' AND anoCriacao < 1700;
DELETE FROM sobremesa WHERE nome = 'Rabanada' AND calorias < 400;
DELETE FROM sobremesa WHERE origem = 'Venezuela' AND calorias <= 300;
DELETE FROM sobremesa WHERE nome = 'Kulfi' AND anoCriacao < 1900;
DELETE FROM sobremesa WHERE origem = 'Peru' AND calorias > 250;
DELETE FROM sobremesa WHERE nome = 'Dulce de Leche' AND origem = 'Argentina';
DELETE FROM sobremesa WHERE anoCriacao BETWEEN 1800 AND 1900;
DELETE FROM sobremesa WHERE calorias = 150;
DELETE FROM sobremesa WHERE nome = 'Sopaipilla' AND origem = 'Chile';
DELETE FROM sobremesa WHERE origem = 'Egito' AND calorias > 300;
DELETE FROM sobremesa WHERE nome = 'Jalebi' AND anoCriacao < 1600;
DELETE FROM sobremesa WHERE nome = 'Natilla' AND origem = 'Colombia';
DELETE FROM sobremesa WHERE nome = 'Rasgulla' AND calorias = 250;
DELETE FROM sobremesa WHERE origem = 'LIbano' AND anoCriacao < 1500;
DELETE FROM sobremesa WHERE nome = 'Pastel de Belem' AND calorias < 350;
DELETE FROM sobremesa WHERE origem = 'Palestina' AND anoCriacao < 1600;
DELETE FROM sobremesa WHERE calorias > 400;
DELETE FROM sobremesa WHERE nome = 'Ensaimada' AND origem = 'Espanha';
DELETE FROM sobremesa WHERE nome = 'Baklava' AND calorias <= 300;
DELETE FROM sobremesa WHERE origem = 'Africa do Sul' AND anoCriacao > 1600;
DELETE FROM sobremesa WHERE nome = 'Merengon' AND calorias < 350;
DELETE FROM sobremesa WHERE origem = 'Turquia' AND nome LIKE '%de%';
