UPDATE sobremesa SET anoCriacao = 1650 WHERE nome = 'Mazamorra Morada';
UPDATE sobremesa SET origem = 'Espanha' WHERE nome = 'Teja';
UPDATE sobremesa SET calorias = 310 WHERE nome = 'Quesillo';
UPDATE sobremesa SET anoCriacao = 1650 WHERE nome = 'Cocada Amarela';
UPDATE sobremesa SET origem = 'Namíbia' WHERE nome = 'Malva Pudding';
UPDATE sobremesa SET calorias = 320 WHERE nome = 'Koeksister';
UPDATE sobremesa SET nome = 'Lamington de Chocolate' WHERE nome = 'Lamington';
UPDATE sobremesa SET calorias = 210 WHERE nome = 'Anmitsu';
UPDATE sobremesa SET anoCriacao = 1800 WHERE nome = 'Daifuku';
UPDATE sobremesa SET origem = 'Brasil' WHERE nome = 'Pastel de Belem';
UPDATE sobremesa SET calorias = 260 WHERE nome = 'Picarones';
UPDATE sobremesa SET origem = 'Peru' WHERE nome = 'Sopaipilla';
UPDATE sobremesa SET calorias = 310 WHERE nome = 'Capirotada';
UPDATE sobremesa SET origem = 'Portugal' WHERE nome = 'Arroz con Leche';
UPDATE sobremesa SET anoCriacao = 1700 WHERE nome = 'Natilla';
UPDATE sobremesa SET calorias = 290 WHERE nome = 'Arequipe';
UPDATE sobremesa SET nome = 'Merengue Colombiano' WHERE nome = 'Merengon';
UPDATE sobremesa SET calorias = 420 WHERE nome = 'Turron';
UPDATE sobremesa SET anoCriacao = 1400 WHERE nome = 'Polvoron';
UPDATE sobremesa SET origem = 'Mexico' WHERE nome = 'Rosquillas';
UPDATE sobremesa SET calorias = 360 WHERE nome = 'Ensaimada';
UPDATE sobremesa SET origem = 'França' WHERE nome = 'Leche Frita';
UPDATE sobremesa SET anoCriacao = 1650 WHERE nome = 'Qatayef';
UPDATE sobremesa SET origem = 'Síria' WHERE nome = 'Basbousa';
UPDATE sobremesa SET calorias = 410 WHERE nome = 'Kanafeh';
UPDATE sobremesa SET nome = 'Maamoul de Tâmara' WHERE nome = 'Maamoul';
UPDATE sobremesa SET anoCriacao = 1470 WHERE nome = 'Baklava';
UPDATE sobremesa SET calorias = 180 WHERE nome = 'Loukoumades';
UPDATE sobremesa SET origem = 'Turquia' WHERE nome = 'Galaktoboureko';
UPDATE sobremesa SET anoCriacao = 1580 WHERE nome = 'Revani';
UPDATE sobremesa SET calorias = 270 WHERE nome = 'Sutlaç';
UPDATE sobremesa SET origem = 'Grécia' WHERE nome = 'Kazandibi';
UPDATE sobremesa SET anoCriacao = 1750 WHERE nome = 'Lokum';
UPDATE sobremesa SET calorias = 360 WHERE nome = 'Kadaif';
UPDATE sobremesa SET nome = 'Gajar Halwa' WHERE nome = 'Gajar ka Halwa';
UPDATE sobremesa SET calorias = 240 WHERE nome = 'Rasgulla';
UPDATE sobremesa SET origem = 'Bangladesh' WHERE nome = 'Sandesh';
UPDATE sobremesa SET anoCriacao = 1600 WHERE nome = 'Jalebi';
UPDATE sobremesa SET calorias = 260 WHERE nome = 'Barfi';
UPDATE sobremesa SET nome = 'Laddu de Coco' WHERE nome = 'Laddu';
UPDATE sobremesa SET anoCriacao = 1520 WHERE nome = 'Modak';
UPDATE sobremesa SET calorias = 270 WHERE nome = 'Kaju Katli';
UPDATE sobremesa SET calorias = 360 WHERE nome = 'Gulab Jamun';
UPDATE sobremesa SET origem = 'Afeganistão' WHERE nome = 'Rabri';
UPDATE sobremesa SET calorias = 230 WHERE nome = 'Phirni';
UPDATE sobremesa SET anoCriacao = 1400 WHERE nome = 'Sheer Khurma';
UPDATE sobremesa SET calorias = 260 WHERE nome = 'Payasam';
UPDATE sobremesa SET origem = 'Nepal' WHERE nome = 'Kheer';
UPDATE sobremesa SET anoCriacao = 1750 WHERE nome = 'Kulfi';
UPDATE sobremesa SET nome = 'Mochi Recheado' WHERE nome = 'Mochi Ice Cream';
UPDATE sobremesa SET calorias = 410 WHERE nome = 'Tiramisu';
UPDATE sobremesa SET anoCriacao = 1930 WHERE nome = 'Cheesecake';
UPDATE sobremesa SET origem = 'Brasil' WHERE nome = 'Pudim';
UPDATE sobremesa SET calorias = 220 WHERE nome = 'Sorvete';
UPDATE sobremesa SET nome = 'Mousse de Limão' WHERE nome = 'Mousse de Maracuja';
UPDATE sobremesa SET origem = 'Australia' WHERE nome = 'Pavlova';
UPDATE sobremesa SET calorias = 380 WHERE nome = 'Brownie';
UPDATE sobremesa SET anoCriacao = 1600 WHERE nome = 'Macaron';
UPDATE sobremesa SET origem = 'Mexico' WHERE nome = 'Churros';
UPDATE sobremesa SET calorias = 260 WHERE nome = 'Panna Cotta';
UPDATE sobremesa SET origem = 'Italia' WHERE nome = 'Creme Brulee';
UPDATE sobremesa SET anoCriacao = 1900 WHERE nome = 'Gelatina';
UPDATE sobremesa SET nome = 'Quindim de Coco' WHERE nome = 'Quindim';
UPDATE sobremesa SET calorias = 220 WHERE nome = 'Brigadeiro';
UPDATE sobremesa SET origem = 'Portugal' WHERE nome = 'Cocada';
UPDATE sobremesa SET calorias = 270 WHERE nome = 'Pastel de Nata';
UPDATE sobremesa SET anoCriacao = 1975 WHERE nome = 'Banoffee Pie';
UPDATE sobremesa SET origem = 'Portugal' WHERE nome = 'Manjar Branco';
UPDATE sobremesa SET calorias = 260 WHERE nome = 'Baba de Moça';
UPDATE sobremesa SET nome = 'Pé de Moleque Tradicional' WHERE nome = 'Pe de Moleque';
UPDATE sobremesa SET calorias = 210 WHERE nome = 'Beijinho';
UPDATE sobremesa SET calorias = 190 WHERE nome = 'Cajuzinho';
UPDATE sobremesa SET anoCriacao = 1700 WHERE nome = 'Canjica';
UPDATE sobremesa SET calorias = 240 WHERE nome = 'Curau';
UPDATE sobremesa SET anoCriacao = 1700 WHERE nome = 'Arroz Doce';
UPDATE sobremesa SET origem = 'Espanha' WHERE nome = 'Rabanada';
UPDATE sobremesa SET calorias = 360 WHERE nome = 'Sonho';
UPDATE sobremesa SET origem = 'Espanha' WHERE nome = 'Pudim de Leite';
UPDATE sobremesa SET anoCriacao = 1500 WHERE nome = 'Manjar de Coco';
UPDATE sobremesa SET calorias = 260 WHERE nome = 'Baba de Moça com Coco';
UPDATE sobremesa SET origem = 'Africa' WHERE nome = 'Pé de Moleque com Castanha';
UPDATE sobremesa SET nome = 'Beijinho Tradicional' WHERE nome = 'Beijinho de Leite Condensado';
UPDATE sobremesa SET calorias = 180 WHERE nome = 'Cajuzinho de Castanha';
UPDATE sobremesa SET anoCriacao = 1750 WHERE nome = 'Canjica com Leite Condensado';
UPDATE sobremesa SET calorias = 240 WHERE nome = 'Curau com Canela';
UPDATE sobremesa SET origem = 'China' WHERE nome = 'Mochi';
UPDATE sobremesa SET calorias = 320 WHERE nome = 'Baklava';
UPDATE sobremesa SET anoCriacao = 1400 WHERE nome = 'Gulab Jamun';
UPDATE sobremesa SET calorias = 220 WHERE nome = 'Che';
UPDATE sobremesa SET calorias = 280 WHERE nome = 'Kheer';
UPDATE sobremesa SET origem = 'Pakistão' WHERE nome = 'Kulfi';
UPDATE sobremesa SET calorias = 170 WHERE nome = 'Mochi Ice Cream';
UPDATE sobremesa SET calorias = 320 WHERE nome = 'Halo-Halo';
UPDATE sobremesa SET anoCriacao = 1850 WHERE nome = 'Tres Leches';
UPDATE sobremesa SET origem = 'Cuba' WHERE nome = 'Flan';
UPDATE sobremesa SET calorias = 310 WHERE nome = 'Dulce de Leche';
UPDATE sobremesa SET anoCriacao = 1990 WHERE nome = 'Chocotorta';
UPDATE sobremesa SET origem = 'Uruguai' WHERE nome = 'Alfajor';
UPDATE sobremesa SET calorias = 370 WHERE nome = 'Chaja';
UPDATE sobremesa SET calorias = 290 WHERE nome = 'Suspiro Limeño';