
UPDATE sobremesa SET calorias = 360 WHERE anoCriacao < 1600;
UPDATE sobremesa SET calorias = 400 WHERE anoCriacao BETWEEN 1600 AND 1700;
UPDATE sobremesa SET calorias = 250 WHERE anoCriacao > 2000;
UPDATE sobremesa SET calorias = 300 WHERE anoCriacao BETWEEN 1800 AND 1900;
UPDATE sobremesa SET calorias = 220 WHERE anoCriacao < 1000;
UPDATE sobremesa SET origem = 'Itália' WHERE calorias > 350;
UPDATE sobremesa SET origem = 'Brasil' WHERE calorias < 200;
UPDATE sobremesa SET origem = 'França' WHERE calorias BETWEEN 200 AND 300;
UPDATE sobremesa SET origem = 'Japão' WHERE calorias > 400;
UPDATE sobremesa SET origem = 'Índia' WHERE calorias BETWEEN 300 AND 400;
UPDATE sobremesa SET anoCriacao = 2000 WHERE origem = 'Brasil';
UPDATE sobremesa SET anoCriacao = 1500 WHERE origem = 'Espanha';
UPDATE sobremesa SET anoCriacao = 1950 WHERE origem = 'EUA';
UPDATE sobremesa SET anoCriacao = 1800 WHERE origem = 'Portugal';
UPDATE sobremesa SET anoCriacao = 1600 WHERE origem = 'Japão';
UPDATE sobremesa SET origem = 'Desconhecida' WHERE calorias = 250;
UPDATE sobremesa SET origem = 'Europa' WHERE calorias = 350;
UPDATE sobremesa SET origem = 'América Latina' WHERE calorias = 300;
UPDATE sobremesa SET origem = 'Oriente Médio' WHERE calorias = 200;
UPDATE sobremesa SET origem = 'África' WHERE calorias = 150;
UPDATE sobremesa SET anoCriacao = 2021 WHERE calorias > 400;
UPDATE sobremesa SET anoCriacao = 1900 WHERE calorias < 200;
UPDATE sobremesa SET anoCriacao = 1800 WHERE calorias BETWEEN 200 AND 300;
UPDATE sobremesa SET anoCriacao = 1955 WHERE calorias BETWEEN 300 AND 350;
UPDATE sobremesa SET anoCriacao = 1955 WHERE calorias BETWEEN 300 AND 350;
UPDATE sobremesa SET anoCriacao = 1999 WHERE origem = 'Brasil' AND calorias < 250;
UPDATE sobremesa SET anoCriacao = 1985 WHERE origem = 'França' AND calorias BETWEEN 300 AND 400;
UPDATE sobremesa SET anoCriacao = 2015 WHERE origem = 'Índia' AND calorias > 350;
UPDATE sobremesa SET anoCriacao = 2005 WHERE origem = 'Itália' AND calorias < 300;
UPDATE sobremesa SET origem = 'América do Norte' WHERE anoCriacao >= 1900 AND anoCriacao < 2000;
UPDATE sobremesa SET origem = 'América do Sul' WHERE anoCriacao < 1900;
UPDATE sobremesa SET origem = 'Ásia' WHERE anoCriacao >= 1000 AND anoCriacao < 1500;
UPDATE sobremesa SET origem = 'Oriente Médio' WHERE anoCriacao < 1000;
UPDATE sobremesa SET origem = 'Europa' WHERE anoCriacao >= 1600 AND anoCriacao < 1800;
UPDATE sobremesa SET calorias = 500 WHERE nome = 'Tiramisu';
UPDATE sobremesa SET calorias = 420 WHERE nome = 'Cheesecake';
UPDATE sobremesa SET calorias = 280 WHERE nome = 'Pudim';
UPDATE sobremesa SET calorias = 210 WHERE nome = 'Sorvete';
UPDATE sobremesa SET calorias = 260 WHERE nome = 'Mousse de Maracuja';
UPDATE sobremesa SET origem = 'América' WHERE nome = 'Brownie';
UPDATE sobremesa SET origem = 'Europa' WHERE nome = 'Macaron';
UPDATE sobremesa SET origem = 'América do Sul' WHERE nome = 'Quindim';
UPDATE sobremesa SET origem = 'Ásia' WHERE nome = 'Mochi';
UPDATE sobremesa SET origem = 'Oriente Médio' WHERE nome = 'Baklava';
UPDATE sobremesa SET anoCriacao = 2000 WHERE nome = 'Pavlova';
UPDATE sobremesa SET anoCriacao = 1985 WHERE nome = 'Churros';
UPDATE sobremesa SET anoCriacao = 1975 WHERE nome = 'Panna Cotta';
UPDATE sobremesa SET anoCriacao = 1995 WHERE nome = 'Creme Brulee';
UPDATE sobremesa SET anoCriacao = 1600 WHERE nome = 'Sonho';
UPDATE sobremesa SET calorias = 370 WHERE origem = 'Brasil';
UPDATE sobremesa SET calorias = 410 WHERE origem = 'Espanha';
UPDATE sobremesa SET calorias = 380 WHERE origem = 'França';
UPDATE sobremesa SET calorias = 300 WHERE origem = 'Japão';
UPDATE sobremesa SET calorias = 250 WHERE origem = 'Índia';
UPDATE sobremesa SET origem = 'Inglaterra', calorias = 450 WHERE nome = 'Banoffee Pie' AND anoCriacao = 1970;
UPDATE sobremesa SET origem = 'México', calorias = 380 WHERE nome = 'Tres Leches' AND anoCriacao = 1900;
UPDATE sobremesa SET origem = 'Colômbia', calorias = 310 WHERE nome = 'Arequipe' AND anoCriacao = 1800;
UPDATE sobremesa SET origem = 'França', calorias = 320 WHERE nome = 'Macaron' AND anoCriacao < 1600;
UPDATE sobremesa SET origem = 'Itália', calorias = 340 WHERE nome = 'Gelato' AND anoCriacao = 1700;
UPDATE sobremesa SET calorias = 150 WHERE nome = 'Gelatina' AND calorias > 200;
UPDATE sobremesa SET calorias = 220 WHERE nome = 'Pudim de Leite' AND calorias > 300;
UPDATE sobremesa SET calorias = 180 WHERE nome = 'Mochi' AND calorias = 200;
UPDATE sobremesa SET calorias = 200 WHERE nome = 'Anmitsu' AND calorias = 250;
UPDATE sobremesa SET calorias = 160 WHERE nome = 'Rabanada' AND calorias = 300;
UPDATE sobremesa SET origem = 'Vietnã' WHERE nome = 'Che' AND calorias < 250;
UPDATE sobremesa SET origem = 'Japão' WHERE nome = 'Daifuku' AND calorias < 200;
UPDATE sobremesa SET origem = 'Filipinas' WHERE nome = 'Halo-Halo' AND calorias = 300;
UPDATE sobremesa SET origem = 'Peru' WHERE nome = 'Picarones' AND calorias = 250;
UPDATE sobremesa SET origem = 'Líbano' WHERE nome = 'Maamoul' AND calorias < 300;
UPDATE sobremesa SET calorias = 250 WHERE anoCriacao < 1600 AND calorias < 300;
UPDATE sobremesa SET calorias = 300 WHERE anoCriacao BETWEEN 1400 AND 1600 AND calorias < 350;
UPDATE sobremesa SET calorias = 320 WHERE anoCriacao < 1000 AND calorias < 250;
UPDATE sobremesa SET calorias = 270 WHERE anoCriacao BETWEEN 1200 AND 1500 AND calorias < 300;
UPDATE sobremesa SET calorias = 350 WHERE anoCriacao BETWEEN 1500 AND 1800 AND calorias < 400;
UPDATE sobremesa SET origem = 'Desconhecida' WHERE anoCriacao < 1400;
UPDATE sobremesa SET origem = 'Desconhecida' WHERE anoCriacao < 1200;
UPDATE sobremesa SET origem = 'Desconhecida' WHERE anoCriacao < 1000;
UPDATE sobremesa SET origem = 'Desconhecida' WHERE anoCriacao < 500;
UPDATE sobremesa SET anoCriacao = 2000 WHERE nome = 'Brigadeiro';
UPDATE sobremesa SET anoCriacao = 2010 WHERE nome = 'Cheesecake';
UPDATE sobremesa SET anoCriacao = 2020 WHERE nome = 'Sorvete';
UPDATE sobremesa SET anoCriacao = 2015 WHERE nome = 'Mousse de Maracuja';
UPDATE sobremesa SET anoCriacao = 2018 WHERE nome = 'Churros';
UPDATE sobremesa SET calorias = 300, origem = 'Global' WHERE anoCriacao > 2000;
UPDATE sobremesa SET calorias = 250, origem = 'Contemporânea' WHERE anoCriacao > 2015;
UPDATE sobremesa SET calorias = 320, origem = 'Moderna' WHERE anoCriacao BETWEEN 1990 AND 2000;
UPDATE sobremesa SET calorias = 260, origem = 'Inovadora' WHERE anoCriacao > 2010;
UPDATE sobremesa SET calorias = 280, origem = 'Reformulada' WHERE anoCriacao = 2021;

/*5 funções*/ 



