DELETE FROM sobremesa WHERE origem = 'Italia';
DELETE FROM sobremesa WHERE anoCriacao < 1900;
DELETE FROM sobremesa WHERE calorias > 300;
DELETE FROM sobremesa WHERE origem = 'EUA';
DELETE FROM sobremesa WHERE nome = 'Pudim' AND calorias < 400;
DELETE FROM sobremesa WHERE anoCriacao = 1980;
DELETE FROM sobremesa WHERE origem = 'Brasil' AND calorias > 250;
DELETE FROM sobremesa WHERE nome = 'Sorvete' AND origem = 'China';
DELETE FROM sobremesa WHERE calorias BETWEEN 200 AND 300;
DELETE FROM sobremesa WHERE origem = 'França' AND anoCriacao > 1500;
DELETE FROM sobremesa WHERE nome LIKE '%de Leite%';
DELETE FROM sobremesa WHERE calorias = 150;
DELETE FROM sobremesa WHERE nome = 'Churros' AND origem = 'Espanha';
DELETE FROM sobremesa WHERE anoCriacao < 1700;
DELETE FROM sobremesa WHERE origem = 'Portugal' AND calorias <= 300;
DELETE FROM sobremesa WHERE nome = 'Mousse de Maracuja';
DELETE FROM sobremesa WHERE origem = 'Nova Zelândia' AND anoCriacao < 1950;
DELETE FROM sobremesa WHERE calorias > 400;
DELETE FROM sobremesa WHERE nome = 'Brownie' AND origem = 'EUA';
DELETE FROM sobremesa WHERE nome = 'Macaron' AND anoCriacao < 1600;
DELETE FROM sobremesa WHERE origem = 'Espanha' AND calorias < 300;
DELETE FROM sobremesa WHERE nome = 'Panna Cotta' AND calorias <= 250;
DELETE FROM sobremesa WHERE origem = 'Japao' AND anoCriacao > 1900;
DELETE FROM sobremesa WHERE nome = 'Beijinho' AND calorias < 250;
DELETE FROM sobremesa WHERE origem = 'Brasil' AND anoCriacao = 1940;
DELETE FROM sobremesa WHERE nome = 'Quindim' AND calorias = 300;
DELETE FROM sobremesa WHERE origem = 'Argentina' AND anoCriacao < 1900;
DELETE FROM sobremesa WHERE calorias > 350;
DELETE FROM sobremesa WHERE nome = 'Banoffee Pie' AND origem = 'Inglaterra';
DELETE FROM sobremesa WHERE nome = 'Gelatina' AND anoCriacao < 1900;
DELETE FROM sobremesa WHERE origem = 'Filipinas' AND calorias < 300;
DELETE FROM sobremesa WHERE nome = 'Malva Pudding' AND origem = 'Africa do Sul';
DELETE FROM sobremesa WHERE nome = 'Tiramisu' AND anoCriacao > 1950;
DELETE FROM sobremesa WHERE origem = 'India' AND calorias > 300;
DELETE FROM sobremesa WHERE nome LIKE 'Cajuzinho%';
DELETE FROM sobremesa WHERE origem = 'Grecia' AND anoCriacao < 1800;
DELETE FROM sobremesa WHERE calorias = 250;
DELETE FROM sobremesa WHERE nome = 'Capirotada' AND origem = 'Mexico';
DELETE FROM sobremesa WHERE origem = 'Turquia' AND anoCriacao < 1700;
DELETE FROM sobremesa WHERE nome = 'Rabanada' AND calorias < 400;
DELETE FROM sobremesa WHERE origem = 'Venezuela' AND calorias <= 300;
DELETE FROM sobremesa WHERE nome = 'Kulfi' AND anoCriacao < 1900;
DELETE FROM sobremesa WHERE origem = 'Peru' AND calorias > 250;
DELETE FROM sobremesa WHERE nome = 'Dulce de Leche' AND origem = 'Argentina';
DELETE FROM sobremesa WHERE anoCriacao BETWEEN 1800 AND 1900;
DELETE FROM sobremesa WHERE calorias = 150;
DELETE FROM sobremesa WHERE nome = 'Sopaipilla' AND origem = 'Chile';
DELETE FROM sobremesa WHERE origem = 'Egito' AND calorias > 300;
DELETE FROM sobremesa WHERE nome = 'Jalebi' AND anoCriacao < 1600;
DELETE FROM sobremesa WHERE nome = 'Natilla' AND origem = 'Colombia';
DELETE FROM sobremesa WHERE nome = 'Rasgulla' AND calorias = 250;
DELETE FROM sobremesa WHERE origem = 'LIbano' AND anoCriacao < 1500;
DELETE FROM sobremesa WHERE nome = 'Pastel de Belem' AND calorias < 350;
DELETE FROM sobremesa WHERE origem = 'Palestina' AND anoCriacao < 1600;
DELETE FROM sobremesa WHERE calorias > 400;
DELETE FROM sobremesa WHERE nome = 'Ensaimada' AND origem = 'Espanha';
DELETE FROM sobremesa WHERE nome = 'Baklava' AND calorias <= 300;
DELETE FROM sobremesa WHERE origem = 'Africa do Sul' AND anoCriacao > 1600;
DELETE FROM sobremesa WHERE nome = 'Merengon' AND calorias < 350;
DELETE FROM sobremesa WHERE origem = 'Turquia' AND nome LIKE '%de%';

UPDATE sobremesa SET calorias = 500 WHERE nome = 'Tiramisu';
UPDATE sobremesa SET anoCriacao = 1930 WHERE nome = 'Cheesecake';
UPDATE sobremesa SET origem = 'França' WHERE nome = 'Creme Brulee';
UPDATE sobremesa SET calorias = 380 WHERE nome = 'Brownie';
UPDATE sobremesa SET nome = 'Brigadeiro Gourmet', calorias = 250 WHERE origem = 'Brasil';
UPDATE sobremesa SET calorias = 450 WHERE nome = 'Pavlova';
UPDATE sobremesa SET nome = 'Mochi Tradicional', origem = 'Japão' WHERE anoCriacao = 794;
UPDATE sobremesa SET anoCriacao = 1500 WHERE nome = 'Rabanada';
UPDATE sobremesa SET calorias = 400, origem = 'Grécia' WHERE origem = 'Baklava';
UPDATE sobremesa SET calorias = 370 WHERE nome = 'Churros';
UPDATE sobremesa SET calorias = 320 WHERE nome = 'Pudim';
UPDATE sobremesa SET anoCriacao = 1900 WHERE nome = 'Sorvete';
UPDATE sobremesa SET origem = 'Itália' WHERE nome = 'Panna Cotta';
UPDATE sobremesa SET nome = 'Mousse de Maracujá com Chantilly', calorias = 450 WHERE nome = 'Mousse de Maracuja';
UPDATE sobremesa SET origem = 'França' WHERE nome = 'Macaron';
UPDATE sobremesa SET calorias = 420 WHERE nome = 'Quindim';
UPDATE sobremesa SET anoCriacao = 1750 WHERE origem = 'Portugal';
UPDATE sobremesa SET calorias = 380 WHERE nome = 'Banoffee Pie';
UPDATE sobremesa SET calorias = 250, origem = 'Brasil' WHERE nome = 'Beijinho';
UPDATE sobremesa SET anoCriacao = 1950, calorias = 400 WHERE nome = 'Cocada';

/* 5 Funções*/
SELECT LENGTH(nome) FROM sobremesa;
SELECT UPPER(nome) FROM sobremesa;
SELECT LOWER(nome) FROM sobremesa;
SELECT REPLACE(nome, 'Pudim', 'Pudding') FROM sobremesa;
SELECT SUBSTRING(nome, 1, 5) FROM sobremesa;